on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build-beta:
    name: Build latest NodeBB
    runs-on: ubuntu-latest
    steps:
      - id: NodeBB-beta
        uses: pozetroninc/github-action-get-latest-release@master
        with:
            owner: NodeBB
            repo: NodeBB
      - uses: actions/checkout@v2

      - name: Build and publish on Github (beta)
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          RELEASE: ${{ steps.NodeBB-beta.outputs.release }}
        with:
         name: rez0n/nodebb
         registry: ghcr.io
         username: "rez0n"
         password: ${{ secrets.PAT }}
         dockerfile: Dockerfile
         buildargs: RELEASE
         tags: beta, ${{ steps.NodeBB-beta.outputs.release }}

      - name: Build and publish on DockerHub (beta)
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          RELEASE: ${{ steps.NodeBB-beta.outputs.release }}
        with:
         name: nibrev/nodebb
         registry: registry.hub.docker.com
         username: "nibrev"
         password: ${{ secrets.DOCKERHUB_TOKEN }}
         dockerfile: Dockerfile
         buildargs: RELEASE
         tags: beta, ${{ steps.NodeBB-beta.outputs.release }}

  build-stable:
    name: Build latest NodeBB
    runs-on: ubuntu-latest
    steps:

      - id: NodeBB-stable
        uses: pozetroninc/github-action-get-latest-release@master
        with:
            owner: NodeBB
            repo: NodeBB
            excludes: prerelease, draft
      - uses: actions/checkout@v2

      - name: Build and publish on Github (stable)
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          RELEASE: ${{ steps.NodeBB-stable.outputs.release }}
        with:
         name: rez0n/nodebb
         registry: ghcr.io
         username: "rez0n"
         password: ${{ secrets.PAT }}
         dockerfile: Dockerfile
         buildargs: RELEASE
         tags: latest, stable, ${{ steps.NodeBB-stable.outputs.release }}

      - name: Build and publish on DockerHub (stable)
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          RELEASE: ${{ steps.NodeBB-stable.outputs.release }}
        with:
         name: nibrev/nodebb
         registry: registry.hub.docker.com
         username: "nibrev"
         password: ${{ secrets.DOCKERHUB_TOKEN }}
         dockerfile: Dockerfile
         buildargs: RELEASE
         tags: latest, stable, ${{ steps.NodeBB-stable.outputs.release }}
